name: rpgland
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

dependencies:
  dotenv: ^4.1.0
  path: ^1.8.3
  teledart: ^0.5.6
  whatsapp_bot_flutter: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
