name: rpgland
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

dependencies:
  dotenv: ^4.1.0
  path: ^1.8.3
  teledart: ^0.5.6
  uuid: ^3.0.7
  json_annotation: ^4.8.1
  mongo_dart: ^0.9.1
  get_it: ^7.6.0
  collection: ^1.17.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.5